01.rgb ppm.md
Likilee/mini_raytracing_in_c pull request #7
Opened 2021-01-17 06:05 UTC by hyongti

01.rgb_ppm.md 끼엑

2021-01-17 08:52 UTC, Likilee requested changes

2021-01-17 08:52 UTC, Likilee commented on 01.rgb_ppm.md
> +만저, 우리가 작성한 코드를 확인할 ppm이미지 파일이다. JPG나 PNG, BMP와 같이 그래픽 파일 포맷 중의 하나이다.(자세한 내용은 [위키피디아](https://en.wikipedia.org/wiki/Netpbm) 참고.) 형식은 이미지2와 같다. 첫 번째 줄의 P3은 아스키코드로 표현한 RGB를 통해 이미지를 표현한다는 뜻이고, 네 번째 줄의 3
만저 유감 ㅜㅜ 코드를 확인할 ppm 파일이라는 말이 어색하게 느껴집니당

2021-01-17 08:52 UTC, Likilee commented on 01.rgb_ppm.md
> +PPM 파일에서 RGB 값의 범위는 0부터 255사이의 정수이지만, 실습에서는 RGB 값을 구할 때 범위를 0부터 1사이의 실수로 매핑하여 사용한 뒤 다시 0부터 255 사이의 정수로 변환하여 출력할 것이다. 여러가지 이유가 있겠지만, 벡터 연산을 통해 구한 값을 이용해 색을 표현하고, [0, 255]보다 더 큰 범위로 색을 표현할 때 확장성을 고려한 것
우리가 만드는 교재인데 아닐까 생각한다는 추측성멘트는 부적합하다고 느꼅집니당
몇가지 이점이 있는데 그 중 이런것도 있다? 식의 표현이 어울릴거 같아용!

2021-01-18 02:30 UTC, minje70 commented
저도 기훈이 형이 말씀하신 부분빼고는 다 괜찮다고 생각합니다!!

2021-01-18 06:03 UTC, hyongti commented on 01.rgb_ppm.md
> +PPM 파일에서 RGB 값의 범위는 0부터 255사이의 정수이지만, 실습에서는 RGB 값을 구할 때 범위를 0부터 1사이의 실수로 매핑하여 사용한 뒤 다시 0부터 255 사이의 정수로 변환하여 출력할 것이다. 여러가지 이유가 있겠지만, 벡터 연산을 통해 구한 값을 이용해 색을 표현하고, [0, 255]보다 더 큰 범위로 색을 표현할 때 확장성을 고려한 것
감사합니당ㅎㅎ

2021-01-18 06:03 UTC, hyongti commented on 01.rgb_ppm.md
> +만저, 우리가 작성한 코드를 확인할 ppm이미지 파일이다. JPG나 PNG, BMP와 같이 그래픽 파일 포맷 중의 하나이다.(자세한 내용은 [위키피디아](https://en.wikipedia.org/wiki/Netpbm) 참고.) 형식은 이미지2와 같다. 첫 번째 줄의 P3은 아스키코드로 표현한 RGB를 통해 이미지를 표현한다는 뜻이고, 네 번째 줄의 3
ㅋㅋㅋ만저 ㅋㅋ 알겠삼당!!

2021-01-19 13:37 UTC, closed without merging